name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r Requirements.txt
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller ^
          --onefile ^
          --windowed ^
          --hidden-import=pythoncom ^
          --hidden-import=win32com ^
          --hidden-import=fitz ^
          --add-data "30.signed.pdf;." ^
          --add-data "hd36vptw-01 (3).pdf;." ^
          --add-data "Vietnamese.dic;." ^
          Chinh38.py

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: Chinh38-Windows
        path: dist/*.exe
